// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzXSha5txWUtjaRunA1WTCBG5W0V3qas',
    appId: '1:459417578776:web:b089bd0889ffc70750026d',
    messagingSenderId: '459417578776',
    projectId: 'newblog-2831f',
    authDomain: 'newblog-2831f.firebaseapp.com',
    storageBucket: 'newblog-2831f.appspot.com',
    measurementId: 'G-61TJS03T39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy61I8OMbkGo7o_g_DMkyjyLE7NmWcNqs',
    appId: '1:459417578776:android:773a2e909938c20b50026d',
    messagingSenderId: '459417578776',
    projectId: 'newblog-2831f',
    storageBucket: 'newblog-2831f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAiynwhmunfI6NnmHnC6Thzd3FhpXHHIA',
    appId: '1:459417578776:ios:5626a4097b1fa8a050026d',
    messagingSenderId: '459417578776',
    projectId: 'newblog-2831f',
    storageBucket: 'newblog-2831f.appspot.com',
    iosClientId: '459417578776-9nkqr6tf3q09mcp798s9fakj1j9g9ntr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAiynwhmunfI6NnmHnC6Thzd3FhpXHHIA',
    appId: '1:459417578776:ios:5626a4097b1fa8a050026d',
    messagingSenderId: '459417578776',
    projectId: 'newblog-2831f',
    storageBucket: 'newblog-2831f.appspot.com',
    iosClientId: '459417578776-9nkqr6tf3q09mcp798s9fakj1j9g9ntr.apps.googleusercontent.com',
    iosBundleId: 'com.example.newblog',
  );
}
